Yet another stab in the dark
HOW DOES ANY OF THIS ACTUALLY WORK.

This only seems to fail in production when booting the instance, but not when
this script executes at runtime.

	java.lang.ClassCastException: [Lhudson.tools.ToolInstallation; cannot be cast to [Lhudson.plugins.git.GitTool;
		at hudson.plugins.git.GitTool.getInstallations(GitTool.java:68)
		at hudson.plugins.git.GitTool.onLoaded(GitTool.java:127)
	Caused: java.lang.reflect.InvocationTargetException
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	Caused: java.lang.Error
		at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
		at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
		at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
		at jenkins.model.Jenkins$7.runTask(Jenkins.java:1090)
		at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
		at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)
	Caused: org.jvnet.hudson.reactor.ReactorException
		at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:269)
		at jenkins.InitReactorRunner.run(InitReactorRunner.java:47)
		at jenkins.model.Jenkins.executeReactor(Jenkins.java:1124)
		at jenkins.model.Jenkins.<init>(Jenkins.java:929)
		at hudson.model.Hudson.<init>(Hudson.java:86)
		at hudson.model.Hudson.<init>(Hudson.java:82)
		at hudson.WebAppMain$3.run(WebAppMain.java:235)
	Caused: hudson.util.HudsonFailedToLoad
		at hudson.WebAppMain$3.run(WebAppMain.java:252)